steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-193", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-193"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "backend-193"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend-193"
      - "--port"
      - "3000"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - |
        DB_NAME=${_DB_NAME},
        DB_USER=${_DB_USER},
        DB_PASS=${_DB_PASS},
        DB_HOST=${_DB_HOST},
        ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},
        REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET}

options:
  logging: CLOUD_LOGGING_ONLY
